baseURL = "https://garvitsingh.com/"
languageCode = "en-us"
title = "Garvit Singh Blogs"
theme = "newsroom"
defaultMode = "light"
enableRobotsTXT = true
[params]
favicon = "static/favicon.ico"

[minify]
  minifyOutput = true