baseURL = "https://garvitsingh.com/"
languageCode = "en-us"
title = "Garvit Singh Blogs"
theme = "newsroom"
defaultMode = "light"
enableRobotsTXT = true

[minify]
  minifyOutput = true

[params.meta]
    favicon = false

[markup.tableOfContents]
  startLevel = 1
  endLevel = 4
  ordered = false # Set to true for numbered lists
