baseURL = "https://garvitsingh.com/"
languageCode = "en-us"
title = "Garvit Singh Blogs"
theme = "newsroom"
defaultMode = "light"
enableRobotsTXT = true

[minify]
  minifyOutput = true

[params.meta]
    favicon = false